auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Yogayu.com
url: https://Yogayu.github.com
feed: /atom.xml
author_info: <a href="https://Yogayu.github.com">youxinyu</a>
