auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: youxinyu.com
url: https://github.com/Yogayu/youxinyu.github.io
feed: /atom.xml
author_info: <a href="https://github.com/Yogayu/youxinyu.github.io">youxinyu</a>
