name: Azure Yu
author: Youxinyu
baseurl:
description: Love Life, Love Nature
github: https://github.com/Yogayu
email: yudelovesong@icould.com

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
analytics:
    provider: custom