# Site settings
title: AzureYu
SEOTitle: AzureYu | 游薪渝的博客
header-img: img/home-bg.jpg
email: yudelovesong@icloud.com
description: "思量阅读，用心码字，业余弹琴"
keyword: "iOS,developer,software,azureyu,游薪渝"
url: "http://azureyu.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

gems: [jekyll-paginate]
gem : 'pygments.rb'

# SNS settings
RSS: true
weibo_username:     u/5639257977
zhihu_username:     youxinyu
github_username:    Yogayu
#twitter_username:  
#facebook_username:  



# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true 

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: yogayu

# Duoshuo settings
#duoshuo_username: yogayu
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 7e918b457095c138d6ce710350596dfc
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: azureyu



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "思量阅读，用心码字，业余弹琴"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
#friends: [
#    {
#        title: "Hux Blog",
#        href: "http://huangxuan.me"
#    }
#]

