name: Azure Yu
author: AzureYu
baseurl: /Azure Yu
description: Love life, Love nature 
github: https://github.com/Yogayu/Yogayu.github.io
twitter: http://www.twitter.com/
email: yudelovesong@icould.com

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
