# Site settings
title: Azure Yu
header-img: img/home-bg.jpg
email: yudelovesong@icould.com
description: "科技的人文关怀"
baseurl: ""
url: "http://azureyu.com"
twitter_username: azureyu
github_username: Yogayu
##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"



